# Generated by Django 5.1.1 on 2024-10-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerstats',
            name='shot_details',
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='app.game'),
        ),
        migrations.AlterField(
            model_name='playerstats',
            name='minutes_played',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Shot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_x', models.FloatField()),
                ('location_y', models.FloatField()),
                ('is_make', models.BooleanField(default=False)),
                ('player_stats', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='app.playerstats')),
            ],
        ),
    ]
