# Generated by Django 5.1.1 on 2024-10-07 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_playerstats_gameplayerstats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='game_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='player_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='team_id',
            new_name='id',
        ),
    ]
