# Generated by Django 5.1.1 on 2024-10-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_game_id_game_id_rename_player_id_player_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameplayerstats',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.team'),
        ),
    ]
